function setLevel (_1: number) {
    tiles.setCurrentTilemap(tilemap`level1`)
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    skibidiToilet.vy = -250
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
    if (info.score() == 6) {
        game.showLongText("You will face Tralalerotralala next.", DialogLayout.Center)
        setLevel(2)
    }
})
let skibidiToilet: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
skibidiToilet = sprites.create(assets.image`skibidiToilet`, SpriteKind.Player)
controller.moveSprite(skibidiToilet, 100, 100)
scene.cameraFollowSprite(skibidiToilet)
skibidiToilet.ay = 600
let tongtongtongtongtongSahur = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Enemy)
tongtongtongtongtongSahur.setVelocity(99, 99)
tongtongtongtongtongSahur.follow(skibidiToilet)
let projectile = sprites.createProjectileFromSprite(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, tongtongtongtongtongSahur, 69, 69)
info.setScore(0)
setLevel(1)
